---

- name: Check if spaCy data is installed.
  register: spacy
  stat:
    path: '{{ osp_src }}/env/lib/python3.4/site-packages/spacy/en/data'

- name: Ensure /tmp/data is empty
  when: not spacy.stat.exists
  file:
    path: /tmp/data
    state: absent

- name: Install spaCy data
  command: env/bin/python3 -m spacy.en.download
  when: not spacy.stat.exists
  args:
    chdir: '{{ osp_src }}'
