---

- name: Configure OSP workers
  sudo: yes
  hosts:
    - tag_osp_server
    - tag_osp_worker
    - tag_osp_render

  vars_files:
    - vars/elasticsearch.yml
    - vars/postgres.yml

  roles:
    - common
    - postgres
    - elasticsearch
    - redis
    - supervisor
    - nginx
