---

- name: Configure an OSP worker set
  sudo: yes
  hosts: tag_osp_worker

  vars_files:
    - vars/passwords.yml
    - vars/elasticsearch.yml
    - vars/postgres.yml

  roles:
    - common
    - postgres
    - elasticsearch
    - redis
    - supervisor
    - nginx
