---

ec2_region: us-east-1
ec2_subnet_id: '{{ lookup("env", "OSP_SUBNET_ID") }}'
ec2_keypair: '{{ lookup("env", "OSP_KEYPAIR") }}'
ec2_osp_snapshot: '{{ lookup("env", "OSP_CORPUS_SNAPSHOT") }}'
ec2_image: ami-9eaa1cf6

ec2_worker_instance_type: t2.micro
ec2_worker_count: 2
